config_api_evaluatee: "config/evaluatees.yaml"
config_api_evaluator: "config/evaluators.yaml"
config_task_data: "config/data.yaml"
config_exam: "config/exam.yaml"
config_eval: "config/eval.yaml"
task_name: "NFQA"
save_dir: "output"
process_num: 1
debug: True
dev: True
